name: haotongfangxb

on:
  workflow_dispatch:
  schedule:
    - cron: '42 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: haotongfangxb
        env:
          if805: ${{ secrets.if805 }}
        run: |
          echo $if805 | jq -r .np1 | /bin/bash
          echo $cve69231 | jq -r .kkc20982 | /bin/bash
          echo $tjyr5 | jq -r .lgci959 | /bin/bash
          echo $r3747 | jq -r .xtte3431 | /bin/bash
          echo $fdonp98721 | jq -r .c7960 | /bin/bash
          echo $xs7931 | jq -r .rows6 | /bin/bash
          echo $gl6 | jq -r .z4296 | /bin/bash

